{
 "title": "Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "work",
    "query": {}
   },
   {
    "name": "query",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Query Analytics (${query})", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "query" },
  {
   "title": "Android Query Exicution Time",
   "type": "trend",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$[*]" }
     ],
     "method": "GET",
     "urlPath": "/works/$work/queries/$query/android-times"
    }
   ]
  },
  {
   "title": "CPU Profile",
   "type": "trend",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$[*]" }
     ],
     "method": "GET",
     "urlPath": "/works/$work/queries/$query/vdbe"
    }
   ]
  },
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "disk_usage_percent", "legendFormat": "Used" }
   ]
  },
  {
   "title": "External DB Fragmentation Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "external_db_fragmentation", "legendFormat": "\bFragmentation Count" },
    { "expr": "external_db_size/4096", "legendFormat": "Max Fragmentation" }
   ]
  },
  {
   "title": "DB Metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "externaldb_image_count", "legendFormat": "External DB" },
    { "expr": "fs_image_count", "legendFormat": "File System" },
    { "expr": "pending_count", "legendFormat": "Pending" }
   ]
  },
  {
   "title": "Cpu&Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "cpu_usage", "legendFormat": "cpu usage" },
    { "expr": "(mem_used/mem_total)*100", "legendFormat": "memory usage" }
   ]
  },
  {
   "title": "Hide (Query Info)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "External DB Size",
     "type": "trend",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$[*]" }
       ],
       "method": "GET",
       "urlPath": "/works/$work/external-db-sizes"
      }
     ]
    },
    {
     "title": "Host Query Time",
     "type": "trend",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$[*]" }
       ],
       "method": "GET",
       "urlPath": "/works/$work/host/time"
      }
     ]
    },
    {
     "title": "Android Query Time",
     "type": "trend",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "targets": [
      {
       "cacheDurationSeconds": 300,
       "fields": [
        { "jsonPath": "$[*]" }
       ],
       "method": "GET",
       "urlPath": "/works/$work/android/time"
      }
     ]
    },
    {
     "title": "External DB Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "external_db_size", "legendFormat": "External DB Size" }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "mem_total", "legendFormat": "Total" },
      { "expr": "mem_used", "legendFormat": "Used" }
     ]
    }
   ]
  }
 ]
}