version: '3.3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: alpainfra-prometheus
    restart: unless-stopped
    expose:
      - 9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    extra_hosts:
      - 'host.docker.internal:${HOST_IP}'
  grafana:
    image: grafana/grafana:10.4.4
    depends_on:
      - prometheus
    ports:
      - ${GRAFANA_PORT}:3000
    restart: unless-stopped
    volumes:
      # - grafana-data:/var/lib/grafana
      # - grafana-plugins:/var/lib/grafana/plugins
      # - grafana-provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: $GRAFANA_ADMIN_USER
      GF_SECURITY_ADMIN_PASSWORD: $GRAFANA_ADMIN_PASSWORD
      GF_INSTALL_PLUGINS: marcusolsson-json-datasource
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_SECURITY_X_FRAME_OPTIONS: sameorigin
    extra_hosts:
      - 'host.docker.internal:${HOST_IP}'
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - ${FRONT_PORT}:80
  #api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   ports:
  #     - ${API_PORT}:3000

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  grafana-plugins:
    driver: local
  grafana-provisioning:
    driver: local
