apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    version: 1
    editable: false
    isDefault: true
  - name: Api
    uid: api
    type: marcusolsson-json-datasource
    url: http://host.docker.internal:3000